[tool.poetry]
name = "website"
version = "0.1.0"
description = ""
authors = ["Vishwas Gowda <vishwas.g217@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
